#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define ACTARUS_TOTAL_INTERRUPTS 512

// TODO(Darleanow): Determine installed ram to auto adapt heap size
#define ACTARUS_HEAP_SIZE_BYTES 104857600
#define ACTARUS_HEAP_BLOCK_SIZE 4096
#define ACTARUS_HEAP_ADDRESS 0x01000000
#define ACTARUS_HEAP_TABLE_ADDRESS 0x00007E00

#define ACTARUS_SECTOR_SIZE 512

// TODO(Darleanow): Maybe add more ?
#define ACTARUS_MAX_FILESYSTEMS 12
#define ACTARUS_MAX_FILE_DESCRIPTORS 512

#define ACTARUS_MAX_PATH 108

#define ACTARUS_TOTAL_GDT_SEGMENTS 6

#define ACTARUS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define ACTARUS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define ACTARUS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define ACTARUS_PROGRAM_VIRTUAL_STACK_ADDRESS_END (ACTARUS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - ACTARUS_USER_PROGRAM_STACK_SIZE)

#define ACTARUS_MAX_PROGRAM_ALLOCATIONS 1024 // TODO(Darleanow): Increase ?

#define ACTARUS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif
