#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define ACTARUS_TOTAL_INTERRUPTS 512

// TODO(Darleanow): Determine installed ram to auto adapt heap size
#define ACTARUS_HEAP_SIZE_BYTES 104857600 // 100MB
#define ACTARUS_HEAP_BLOCK_SIZE 4096
#define ACTARUS_HEAP_ADDRESS 0x01000000
#define ACTARUS_HEAP_TABLE_ADDRESS 0x00007E00

#define ACTARUS_SECTOR_SIZE 512

// TODO(Darleanow): Maybe add more ?
#define ACTARUS_MAX_FILESYSTEMS 12
#define ACTARUS_MAX_FILE_DESCRIPTORS 512
#endif
